#!/bin/bash
#
# A simple script to download the current month's Crypto-Gram issue and import
# it in my Calibre library.
# 
# Requirements: cURL, ImageMagik, Calibre (duh!), Zenity
#

export LANG=en_US.utf8
export LC_ALL=en_US.utf8

#
# Removes the menus and other accessory content from the Crypto-Gram
# web page. All the main content is kept inside a
# <td class="contentcell">...</td>
#
# Usage: declutterize input.html outpout.html
#
function declutterize
{
	INFILE="$1"
	OUTFILE="$2"

	OLD_IFS="$IFS"
	IFS=$'\n'
	BEGIN_WRITE=''
	END_WRITE=''
	cat > "$OUTFILE" << EOF
<html>
<head>
<title>Crypto-Gram - $(date +'%B %Y') issue</title>
</head>
<body>
EOF
	for LINE in $(cat "$INFILE")
	do
		if [ -z "$BEGIN_WRITE" ]
		then
			BEGIN_WRITE=$(echo "$LINE" | grep '<div id="content">')
		else
			if [ -z "$END_WRITE" ]
			then
				echo "$LINE" >> "$OUTFILE"
				END_WRITE=$(echo "$LINE" | grep '</div><!--#content-->')
			fi
		fi
	done

	cat >> "$OUTFILE" << EOF
</body></html>
EOF
}

################################################################################
##### Checks if the user has requested command line help
################################################################################

if [ "$1" == '-h' -o "$1" == '--help' ]
then
    echo
    echo "Usage: $0"
    echo
    echo 'Puts the latest issue of Crypto-Gram into your Calibre database'
    exit
fi

################################################################################
##### Checks for software needed to run the script
################################################################################

( which zenity > /dev/null ) || ZENITY=no
if [ "$ZENITY" == 'no' ]
then
    echo 'ERROR: you need to install Zenity to run Webpage to Calibre'
    exit
fi

(( which montage && which mogrify ) > /dev/null ) || IMAGEMAGICK=no
if [ "$IMAGEMAGICK" == 'no' ]
then
    zenity --error \
            --title='Crypto-Gram to Calibre' \
            --text='You need to install ImageMagick to run Crypto-Gram to Calibre'
    exit
fi

(( which web2disk && \
    which ebook-convert && \
    which ebook-meta && \
    which calibredb ) > /dev/null ) || CALIBRE=no
if [ "$CALIBRE" == 'no' ]
then
    zenity --error \
            --title='Crypto-Gram to Calibre' \
            --text='You need to install Calibre to run Crypto-Gram to Calibre (duh!)'
    exit
fi

################################################################################
##### Prepares the paths variables and the temporary directories
################################################################################

TITLE="Crypto-Gram - $(date +'%B %Y') issue"
OLD_PWD="$(pwd)"
TMP_DIR="$HOME/.cryptogram2calibre"
HTML_DIR="$TMP_DIR/html"
SCRIPT_PATH=$(cd ${0%/*} && echo $PWD/${0##*/})
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
rm -fr "$TMP_DIR"
mkdir -p "$HTML_DIR"
cd "$TMP_DIR"

( # Here starts the code tracked by zenity's progress bar

################################################################################
##### Determines the URL to retrieve and the title of the webpage
################################################################################

URL=$(curl 'https://www.schneier.com/crypto-gram/' \
	| grep -o '<a .*href="https://www.schneier.com/crypto-gram/archives/.*>' \
	| sed -e 's/<a /\n<a /g' \
	| sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' \
	| head -n1)
echo 20

################################################################################
##### Prepares the cover image
################################################################################

montage \
    -label "${TITLE}" \
    "$SCRIPT_DIR/cryptogram-cover-template.jpg" \
    -geometry +0+0 -pointsize 21 -frame 3 \
    cover.jpg > /dev/null
mogrify -resize 590x754! cover.jpg > /dev/null
echo 40

################################################################################
##### Creates the ZIP bundle containing the HTML page
################################################################################

web2disk -d "$HTML_DIR" -r 0 --verbose "$URL" > /dev/null
HTML_FILE=$(echo "$HTML_DIR/"*.xhtml | head -n1)
declutterize "$HTML_FILE" "$HTML_DIR/index.html"
zip -r pippo.zip html   # I don't use HTML_DIR to not clutter the .ZIP internal paths
echo 60

################################################################################
##### Creates the alternative formats
################################################################################

# Direct conversion from HTML to EPUB or PDF gives the following error:
# ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes
ebook-convert pippo.zip pippo.mobi --no-inline-toc --cover=cover.jpg > /dev/null
ebook-convert pippo.mobi pippo.epub --preserve-cover-aspect-ratio --dont-split-on-page-breaks --cover=cover.jpg > /dev/null
echo 80

################################################################################
##### Adds the EPUB to Calibre with appropriate metadata
################################################################################

ebook-meta pippo.epub \
    --cover=cover.jpg \
    --title="$TITLE" \
	--authors='Bruce Schneier' \
	--author-sort='Schneier, Bruce' \
	--tags='Crypto-Gram' \
    > /dev/null

calibredb add pippo.epub > /dev/null

################################################################################
##### Adds the MOBI to Calibre
################################################################################

ebook-meta pippo.mobi \
    --cover=cover.jpg \
    --title="$TITLE" \
	--authors='Bruce Schneier' \
	--author-sort='Schneier, Bruce' \
	--tags='Crypto-Gram, IT, Security' \
    > /dev/null

QUERY="title:\"=$TITLE\""
ID=$(calibredb list --search "$QUERY" | grep '^[0-9]\+ ' | cut -d' ' -f 1)
calibredb add_format $ID pippo.mobi > /dev/null

echo 100

################################################################################
##### Final cleanup
################################################################################

cd "$OLD_PWD"
#rm -fr "$TMP_DIR"

) |
zenity --progress \
    --title='Crypto-Gram to Calibre' \
    --text="Downloadind and importing webpage '$TITLE'..." \
    --percentage=0

[ "$?" = -1 ] && \
    zenity --error --title='Crypto-Gram to Calibre' --text="Import canceled."

