Document: calibre-utils
Title: Debian calibre-utils Manual
Author: <insert document author here>
Abstract: This manual describes what calibre-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/calibre-utils/calibre-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/calibre-utils/calibre-utils.ps.gz

Format: text
Files: /usr/share/doc/calibre-utils/calibre-utils.text.gz

Format: HTML
Index: /usr/share/doc/calibre-utils/html/index.html
Files: /usr/share/doc/calibre-utils/html/*.html
